### PR TITLE
Always enable (fast) support for AVIF on Debian 12 (Bookworm)

### PR DESCRIPTION
**Pull request by mlocati**
Let's see if we can use the system-provided libaom, libdav1d, libyuv, and libavif on Debian Bookworm.

If so, we'll always enable AVIF support, since we won't need the time-consuming compilation of those dependencies (and `IPE_GD_WITHOUTAVIF` won't be considered).

### CODE REVIEW

**Comment by hbouhadji** [comment]
@mlocati this seems to cause this error:
```
-- Build files have been written to: /tmp/src/tmp.lYfdGvrwuY/my.build
[143/298] Building C object CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o
FAILED: CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o
/usr/bin/cc  -I../ -I. -I../apps -I../common -I../examples -I../stats -I../third_party/libyuv/include -O3 -DNDEBUG -std=c99 -Wall -Wdisabled-optimization -Wextra -Wfloat-conversion -Wformat=2 -Wimplicit-function-declaration -Wlogical-op -Wpointer-arith -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized -Wunused -Wvla -Wstack-usage=100000 -Wundef -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC   -march=armv8.2-a+dotprod+i8mm -MD -MT CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o -MF CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o.d -o CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o   -c ../aom_dsp/arm/aom_convolve8_neon_i8mm.c
cc1: error: invalid feature modifier in '-march=armv8.2-a+dotprod+i8mm'
[144/298] Building C object CMakeFiles/aom_dsp_encoder.dir/aom_dsp/sad_av1.c.o
ninja: build stopped: subcommand failed.
```

tried on two macbook (apple silicon)

**Comment by mlocati** [comment]
@hbouhadji The error you are seeing seems to be part of the compilation process of libaom, is it correct?

**Comment by hbouhadji** [comment]
> @hbouhadji The error you are seeing seems to be part of the compilation process of libaom, is it correct?

Exactly, if I set `IPE_GD_WITHOUTAVIF` I don't have the issue

**Comment by mlocati** [comment]
@hbouhadji What's the version of the operating system of the Docker image you are using?
You can retrieve it by running `cat /etc/os-release` inside your docker container (or in a `RUN` step of your Dockerfile).

**Comment by mlocati** [comment]
As you can deduce from the title of this pull request, this change only applies to Debian 12, whereas you are using Debian 10.

**Comment by mlocati** [comment]
@hbouhadji do you have this issue by using version 2.1.84?
In order to check that, simply replace
https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
with
https://github.com/mlocati/docker-php-extension-installer/releases/download/2.1.84/install-php-extensions
in your Dockerfile

**Comment by hbouhadji** [comment]
> https://github.com/mlocati/docker-php-extension-installer/releases/download/2.1.84/install-php-extensions

Nope don't have the issue with the 2.1.84 version

**Comment by mlocati** [comment]
If so. #883 is probably the cause of the issue. I'm going to check that.

**Comment by hbouhadji** [comment]
> If so. #883 is probably the cause of the issue. I'm going to check that.

If you need to try and don't have an arm device, suggest you to try this for debugging: https://docs.docker.com/build/building/multi-platform/

for the moment i'm setting `IPE_GD_WITHOUTAVIF` and i'm good

**Comment by mlocati** [comment]
@hbouhadji I may have found the fix.

Could you please try replacing

```
https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
```

with

```
https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/libaom-build-dir/install-php-extensions
```

in [your sample Dockerfile](https://github.com/mlocati/docker-php-extension-installer/pull/884#issuecomment-1928941864) and check if installing GD works without setting `IPE_GD_WITHOUTAVIF` ?

**Comment by hbouhadji** [comment]
> @hbouhadji I may have found the fix.
> 
> Could you please try replacing
> 
> ```
> https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
> ```
> 
> with
> 
> ```
> https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/libaom-build-dir/install-php-extensions
> ```
> 
> in [your sample Dockerfile](https://github.com/mlocati/docker-php-extension-installer/pull/884#issuecomment-1928941864) and check if installing GD works without setting `IPE_GD_WITHOUTAVIF` ?

still have the error:

```
-- Build files have been written to: /tmp/src/tmp.vR0qBdbIJp/build
[143/298] Building C object CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o
FAILED: CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o
/usr/bin/cc  -I../ -I. -I../apps -I../common -I../examples -I../stats -I../third_party/libyuv/include -O3 -DNDEBUG -std=c99 -Wall -Wdisabled-optimization -Wextra -Wfloat-conversion -Wformat=2 -Wimplicit-function-declaration -Wlogical-op -Wpointer-arith -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized -Wunused -Wvla -Wstack-usage=100000 -Wundef -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC   -march=armv8.2-a+dotprod+i8mm -MD -MT CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o -MF CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o.d -o CMakeFiles/aom_dsp_common_neon_i8mm_intrinsics.dir/aom_dsp/arm/aom_convolve8_neon_i8mm.c.o   -c ../aom_dsp/arm/aom_convolve8_neon_i8mm.c
cc1: error: invalid feature modifier in '-march=armv8.2-a+dotprod+i8mm'
[144/298] Building C object CMakeFiles/aom_dsp_encoder.dir/aom_dsp/sad_av1.c.o
ninja: build stopped: subcommand failed.
```

**Comment by mlocati** [comment]
@hbouhadji It seems that aom 3.8.1 can't be compiled on Debian 10 with arm architecture ([I've reported this bug](https://bugs.chromium.org/p/aomedia/issues/detail?id=3543)) - the most recent version that works is 3.5.0.

Could you please try replacing

```
https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
```

with

```
https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/aom-debian-10/install-php-extensions
```

in [your sample Dockerfile](https://github.com/mlocati/docker-php-extension-installer/pull/884#issuecomment-1928941864)

**Comment by hbouhadji** [comment]
> @hbouhadji It seems that aom 3.8.1 can't be compiled on Debian 10 with arm architecture ([I've reported this bug](https://bugs.chromium.org/p/aomedia/issues/detail?id=3543)) - the most recent version that works is 3.5.0.
> 
> Could you please try replacing
> 
> ```
> https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
> ```
> 
> with
> 
> ```
> https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/aom-debian-10/install-php-extensions
> ```
> 
> in [your sample Dockerfile](https://github.com/mlocati/docker-php-extension-installer/pull/884#issuecomment-1928941864)

Yep it's working with `aom-debian-10`

**Comment by hbouhadji** [comment]
> > Yep it's working with `aom-debian-10`
> 
> Thanks for checking! I've just published version 2.2.1 with this fix.

Thanks for the fix

**Pull request merged**
