### PR TITLE
Fix xdebug with PHP 7.2/7.3/7.4, xdebug 3.2 GA

### LINKED ISSUE #670: [v1.5.50] Please upgrade xdebug support to latest stable version
Hello,

v1.5.5.0 [still uses](https://github.com/mlocati/docker-php-extension-installer/blob/1.5.50/install-php-extensions#L3422-L3440) beta channel for xdebug 3.2.0 (PHP 8 support)

While http://pecl.php.net/package/xdebug/ 3.2.0 stable version was published, please upgrade script to support stable version !

Thanks in advance

### PR DESCRIPTION
**Pull request by mlocati**
Close #670

### CODE REVIEW

**Comment by scollovati** [comment]
Using the image `php:7.4-apache`
the command `pecl install xdebug` or `pecl install xdebug-3.1.6` do not work. I have to install it from pecl:
```
RUN pecl install xdebug-3.1.6 \
      && docker-php-ext-enable xdebug
```

**Comment by mlocati** [comment]
> the command `pecl install xdebug` or `pecl install xdebug-3.1.6` do not work

@scollovati This project is about the `install-php-extensions` command, not about the `pecl` command.

**Comment by scollovati** [comment]
> > the command `pecl install xdebug` or `pecl install xdebug-3.1.6` do not work
> 
> @scollovati This project is about the `install-php-extensions` command, not about the `pecl` command.

My fault in pasting the commands. I've updated the comment with the right ones that reference this project.

**Comment by mlocati** [comment]
> the command `docker-php-ext-install xdebug` or `docker-php-ext-install xdebug-3.1.6` do not work. 

@scollovati Again, this project is about the `install-php-extensions` command, not about the `docker-php-ext-install` command 😉

**Pull request merged**
