### PR TITLE
Fix installing relay on Ubuntu

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Installing issue was found on https://www.drupal.org/project/redis/issues/3493855

### CODE REVIEW

**Comment by tillkruss** [comment]
Relay doesn't have dedicated builds for Ubuntu, because it's the same kernel as debian.

**Comment by mlocati** [comment]
I'm not going to support ubuntu: this project relies on scripts that are only available in official docker images (which only come in Alpine and Debian flavors).

**Comment by tillkruss** [comment]
@mlocati: Looks like the Drupal project is using their own Ubuntu based containers and then use your installer.

**Comment by mlocati** [comment]
> @mlocati: Looks like the Drupal project is using their own Ubuntu based containers and then use your installer.

Any link?

**Comment by tillkruss** [comment]
@berdir can you post a link for @mlocati?

**Pull request closed without merging**
