### PR TITLE
Add support for imagick on PHP 8.3

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by mvorisek** [comment]
with latest https://github.com/Imagick/imagick/commit/28f27044e435a2b203e32675e942eb8de620ee58 master commit the build passes

**Comment by mlocati** [comment]
Let's wait until they publish a new release

**Comment by mlocati** [comment]
> I think they did :)

@vuryss are you sure? Isn't 3.7.0 (dated Jan 2022) the most recent imagick version?

**Comment by vuryss** [comment]
> > I think they did :)
> 
> @vuryss are you sure? Isn't 3.7.0 (dated Jan 2022) the most recent imagick version?

Sorry it was my mistake, I saw the support of Imagick for PHP 8.3 was merged and released in brefphp/extra-php-extensions and I thought it was the extension itself.

**Comment by ganti** [comment]
I tried to install Imagick and failed spectacularly. There is an open PR at
https://github.com/Imagick/imagick/pull/641

**Comment by ganti** [comment]
fyi imagick is not working with `php:8.3-fpm-alpine3.19`

```
make: *** [Makefile:196: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
ERROR: `make -j8 INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuserBOGHED/install-imagick-3.7.0" install' failed
```

**Comment by annuh** [comment]
Fyi, using the (unreleased) master branch worked for me:
```
install-php-extensions imagick/imagick@master
```

**Comment by jeff1326** [comment]
So what's the status of this PR ?

**Comment by jdreesen** [comment]
Still waiting for imagick to be compatible with PHP 8.3, I guess.

**Comment by Orkin** [comment]
Hello, it is with the use of `imagick/imagick@master` on `install-php-extensions`

**Comment by StrangePeanut** [comment]
Considering that the master branch works just fine, it seems that we are now waiting for a proper release by someone with an appropriate user role. IIRC there is just one such person.

**Comment by pereorga** [comment]
I find this confusing. This is using official `php:` images:

- `install-php-extensions imagick/imagick` used to work fine on PHP 8.3 a few days ago. Most of the time the extension fails to compile now, but sometimes randomly (rarely), it works.
- `install-php-extensions imagick/imagick` seems to work fine on PHP 8.4 beta 3.
- `install-php-extensions imagick/imagick@master` works fine on PHP 8.3.
- `install-php-extensions imagick/imagick@master` fails to compile on PHP 8.4 beta 3.

**Comment by mlocati** [comment]
@pereorga there's nothing I can do about that: it's everything up to the imagick maintainers

**Comment by mvorisek** [comment]
>     * `install-php-extensions imagick/imagick@master` fails to compile on PHP 8.4 beta 3.

Please note there is `develop` branch. You can also use https://github.com/mvorisek/image-php prebuilt images for Alpine or Debian with Imagick ext. included.

**Comment by mlocati** [comment]
After a year we still haven't seen a new release of imagick: I updated this PR with a workaround (a temporary one, I hope).

**Comment by bendavies** [comment]
@mlocati can 8.4 support be added too? thanks!

**Comment by mlocati** [comment]
@bendavies I don't maintain the imagick package: I *just* write some code that installs it.

Do you know an imagick version/commit hash that works for PHP 8.4?

**Comment by bendavies** [comment]
hey @mlocati !

Thanks for the reply.
I just meant can 8.4 be added to data/supported-extensions to see if it passes?
I assumed CI ran off that file.
Apologies if I misunderstood.

Thanks!

**Comment by mvorisek** [comment]
> Do you know an imagick version/commit hash that works for PHP 8.4?

https://github.com/mvorisek/image-php/blob/master/data/8.4-alpine/Dockerfile#L26

**Comment by mlocati** [comment]
Let's see what's happen at #1010

**Pull request merged**
