### PR TITLE
Add support/testing for PHP 8.1

### PR DESCRIPTION
**Pull request by mvorisek**
fixes https://github.com/mlocati/docker-php-extension-installer/issues/271

### CODE REVIEW

**Comment by mvorisek** [comment]
I wonder, how can I add testing against `phpdaily/php` docker images?

**Comment by mlocati** [comment]
I guess tests won't complete because of timeout

**Comment by mvorisek** [comment]
> 
> 
> I guess tests won't complete because of timeout

related with: https://github.com/mlocati/docker-php-extension-installer/issues/275, to overcome the timeout I now added support for extensions provided directly from php sources, which should always compile. Once this PR is merged, I will add support for other extensions in another PR.

**Comment by mvorisek** [comment]
given the efford to maintain this and not having full support to mark specific job as informative only - see https://github.com/actions/toolkit/issues/399 , I am closing this for now

**Comment by mlocati** [comment]
Yep, I'd wait that PHP 8.1 becomes a bit more stable (that is, at least in the beta stage).

**Comment by mvorisek** [comment]
@mlocati PR is passing, most of the extensions are from php-src, thus the build should always pass, can we merge it to reduce the testing time of other extensions?

**Comment by mlocati** [comment]
Sure! I'll wait that those last tests pass

**Comment by mvorisek** [comment]
The CI should be passing, `Check on alpine3.12` issue seems to be related with cached PHP 8.1 alpha1 image, alpha2 is fixed.

**Comment by mlocati** [comment]
> The CI should be passing, `Check on alpine3.12` issue seems to be related with cached PHP 8.1 alpha1 image, alpha2 is fixed.

I restarted the CI jobs

**Comment by mvorisek** [comment]
Alpine v3.12 images are no longer updated.

See https://github.com/docker-library/php/pull/1166 and related pulled tag https://hub.docker.com/_/php?tab=tags&page=1&ordering=last_updated&name=8.1-rc-cli-alpine3.12

Can you please adjust the test script that PHP 8.1+ is not tested againt Alpine 3.12?

**Pull request merged**
