### PR TITLE
add Blackfire PHP Probe

### PR DESCRIPTION
**Pull request by llaville**
Hello, 

It would be great to have the [Blackfire PHP Probe](https://blackfire.io/docs/php/integrations/php-docker) added to PHP supported extensions.

Hope you like idea ? Here is my implementation.

### CODE REVIEW

**Comment by mlocati** [comment]
Yep, that'd be nice!

**Comment by llaville** [comment]
@mlocati Could you explain error I got in https://github.com/mlocati/docker-php-extension-installer/runs/3274480987?check_suite_focus=true and perharps add a note about it on section https://github.com/mlocati/docker-php-extension-installer#how-to-contribute.
Thanks in advance

**Comment by mlocati** [comment]
Sure! I've just updated the [`Formatting code`](https://github.com/mlocati/docker-php-extension-installer#formatting-code) section in the README file.

**Comment by mlocati** [comment]
You need to make `scripts/tests/blackfire` executable

**Comment by llaville** [comment]
👍 thanks to you too

**Comment by llaville** [comment]
@mlocati When did you plan to publish the new version 1.2.54 (with at least blackfire) ?

**Comment by mlocati** [comment]
@llaville done

**Pull request merged**
