### PR TITLE
Add msgpack serializer to Redis extension

### PR DESCRIPTION
**Pull request by einar-hansen**
Test: redis

### CODE REVIEW

**Comment by mlocati** [comment]
It seems that redis doesn't implement this configuration option: https://mlocati.github.io/pecl-info/#redis

**Comment by mlocati** [comment]
We need this change: https://github.com/phpredis/phpredis/pull/2113

**Comment by hertz1** [comment]
Hey @mlocati, phpredis/phpredis#2113 has been merged. I think there are no blocks for this PR now?

**Comment by mlocati** [comment]
@hertz1 They haven't published a new version including it yet: see https://github.com/phpredis/phpredis/pull/2113#issuecomment-1255912998

**Comment by mlocati** [comment]
Superseded by #801

**Pull request closed without merging**
