### PR TITLE
Fix typo in script version warning message

### PR DESCRIPTION
**Pull request by yannoff**
Not a huge typo, anyway... :wink:

### CODE REVIEW

**Comment by mlocati** [comment]
Thanks!

**Comment by yannoff** [comment]
> Thanks!

You're welcome :smile_cat: 

By the way, just for the sake of my own acknowledgement... I can't figure out how this part works:

Given the assignment in [line 20](https://github.com/mlocati/docker-php-extension-installer/blob/master/install-php-extensions#L20), it seems to me that the first condition on [line 22](https://github.com/mlocati/docker-php-extension-installer/blob/master/install-php-extensions#L22) always evaluate to `true` ... Am I missing something here ?

**Comment by mlocati** [comment]
The `IPE_VERSION` variable is updated by https://github.com/mlocati/docker-php-extension-installer/blob/1.2.5/.github/workflows/readme-release.yml#L153 (so you should use the file attached to GitHub releases or the Docker image)

**Comment by mlocati** [comment]
You can see how it works by checking this action for instance: https://github.com/mlocati/docker-php-extension-installer/actions/runs/541214743

**Comment by yannoff** [comment]
> You can see how it works by checking this action for instance: https://github.com/mlocati/docker-php-extension-installer/actions/runs/541214743

Ahhh I see :smile_cat:  Thanks for the clarification  :ok_hand:

I realize I reproduced manually the exact anti-pattern that the warning message is here to prevent... :stuck_out_tongue_closed_eyes:

**Pull request merged**
