### PR TITLE
Add support for Mosquitto

### PR DESCRIPTION
**Pull request by gabe565**

### CODE REVIEW

**Comment by mlocati** [comment]
Thanks! Did you already check if mosquitto works with PHP 8?

**Comment by gabe565** [comment]
I haven't but I'll test it out and make a PR on the documentation if it works!

**Comment by mlocati** [comment]
I tested it today, and it doesn't seem to work: see #190

**Comment by gabe565** [comment]
Ah good to know. Nice use of the CI to test that out. I was just going to try to build it manually.

**Pull request merged**
