### PR TITLE
Support serialize for apcu

### PR DESCRIPTION
**Pull request by fedotov-as**
Test: apcu, igbinary, igbinary+apcu

### CODE REVIEW

**Comment by mlocati** [comment]
Which is the module that requires apcu?

**Comment by fedotov-as** [comment]
> Which is the module that requires apcu?

@mlocati,  igbinary

**Comment by mlocati** [comment]
I tried to compile igbinary alone and after installing apcu.

Here's the outputs of `php --ri igbinary`:

| igbinary | apcu+igbinary |
|---|---|
| igbinary support => enabled<br />igbinary version => 3.2.6<br />igbinary APCu serializer ABI => no<br />igbinary session support => yes<br /><br />Directive => Local Value => Master Value<br />igbinary.compact_strings => On => On | igbinary support => enabled<br />igbinary version => 3.2.6<br />igbinary APCu serializer ABI => 0<br />igbinary session support => yes<br /><br />Directive => Local Value => Master Value<br />igbinary.compact_strings => On => On |

The difference is in the `igbinary APCu serializer ABI` values (`no` vs `0`), which seems to me both turned off...

How can we use apcu with igbinary? I don't see any configurable keys in php.ini:

```
$ php -r 'foreach((new ReflectionExtension("igbinary"))->getINIEntries() as $name => $value) echo "{$name}={$value}\n";'
igbinary.compact_strings=1
```

**Comment by fedotov-as** [comment]
You need to check `apcu` extension.

### Test 1:
```
RUN install-php-extensions igbinary
RUN install-php-extensions apcu
```
screen1

Compile logs:
```
### INSTALLING REMOTE MODULE igbinary ###
...
checking PHP version... PHP 7
checking for APCu includes... not found
```

### Test 2:
```
RUN install-php-extensions apcu
RUN install-php-extensions igbinary
```
screen2

Compile logs:
```
### INSTALLING REMOTE MODULE igbinary ###
...
checking PHP version... PHP 7
checking for APCu includes... APCu in /usr/local/include/php
```

**Comment by mlocati** [comment]
@fedotov-as My question was more about how we can configure igbinary in PHP, not about compile time.

As I wrote above, when igbinary is compiled after apcy, we have that `php --ri igbinary` reports `igbinary APCu serializer ABI => 0`: do you know how can we change this value?

**Pull request merged**
