### PR TITLE
Fix pdo_sqlsrv cannot be installed on Debian Bookworm

### PR DESCRIPTION
**Pull request by ittmann**
Fixes the GPG error public key error from https://github.com/mlocati/docker-php-extension-installer/issues/757

### CODE REVIEW

**Comment by mlocati** [comment]
Please add a commit (it may also be empty) containing `Test: sqlsrv, pdo_sqlsrv` in the commit body.
For example:

```
Trigger tests

Test: sqlsrv, pdo_sqlsrv
```

**Comment by mvorisek** [comment]
The CI needs to adjusted to test Debian 12/Bookworm primary :)

**Comment by ittmann** [comment]
Test extensions fails installing pdo_sqlsrv on bookworm as expected (no msodbcsql packages are available yet, see my comment in https://github.com/mlocati/docker-php-extension-installer/issues/757#issuecomment-1598667008)
```
E: Unable to locate package ^msodbcsql[0-9]+$
E: Couldn't find any package by glob '^msodbcsql[0-9]+$'
E: Couldn't find any package by regex '^msodbcsql[0-9]+$'
```

**Comment by mvorisek** [comment]
https://packages.microsoft.com/debian/11/prod/ should be probably used until fixed by Microsoft

**Comment by ittmann** [comment]
> https://packages.microsoft.com/debian/11/prod/ should be probably used until fixed by Microsoft

ugly hacky, but it does seem to work

**Comment by ittmann** [comment]
Tested with [php:8.2-cli](https://hub.docker.com/layers/library/php/8.2-cli/images/sha256-2d3aac26691b6af027bd240be4a918ac3dd2f767109dd13781161e224314ebec?context=explore) (debian 12 bookworm) and [php:8.2-cli-bullseye](https://hub.docker.com/layers/library/php/8.2-cli-bullseye/images/sha256-a17b80547fa724d1e470d44e628db2a115d27dc533c8c38f05bfba5802e5cf5f?context=explore) 
sqlsrv and pdo_sqlsrv extensions load correctly and connections to SQL Server work

**Comment by ittmann** [comment]
As noted in the commit message, commit https://github.com/mlocati/docker-php-extension-installer/pull/761/commits/11d237a2c2a544a452614522588ce04ef58cf035 should be reverted when msodbcsql becomes available in  https://packages.microsoft.com/debian/12/prod/

If both msodbcsql17 and msodbcsql18 become available then https://github.com/mlocati/docker-php-extension-installer/pull/761/commits/fad307871e1b19916739cdf4b17275665065ee6e should be reverted as well so only msodbcsql18 is installed

**Comment by mvorisek** [comment]
@mlocati can you please review this PR? As it does not fix the complete Bookworm issues (https://github.com/mlocati/docker-php-extension-installer/pull/765#issuecomment-1602951890), what about merging it /wo the CI changes?

**Comment by mlocati** [comment]
I've cherry-picked the commits of this #761: see ##765

Thanks!

**Pull request closed without merging**
