### PR TITLE
Prevent problems while installing package

### PR DESCRIPTION
**Pull request by jeff1326**

### CODE REVIEW

**Comment by mlocati** [comment]
Could you provide more details about this change? Why is it required?

**Comment by jeff1326** [comment]
@mlocati Unfortunately no. My co-worker did the changes on a older version of this repository. He told me he added these almost everywhere until it works and he don't remember which specific package was causing the issue.

As i see this, this won't break anything at least.

**Comment by tarlepp** [comment]
That `ACCEPT_EULA=Y` sounds like mssql related configuration.

**Comment by jeff1326** [comment]
> That `ACCEPT_EULA=Y` sounds like mssql related configuration.
> 
> https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&tabs=cli&pivots=cs1-bash#run-the-container-2

That would make sense since we use it in some projet

**Comment by tarlepp** [comment]
although that accept eula thing should not be happen if you're just installing pdo extension for that - not 100% sure about this.

**Comment by mlocati** [comment]
AFAIK the `ACCEPT_EULA` environment variable should be set to install msodbcsql in an unattended way.
But we should already do that: msodbcsql is already being installed without any issue, isn't it?

I won't set a variable nobody knows why and when it should be set...

**Pull request closed without merging**
