### PR TITLE
Fixed gd's compile failure.

### PR DESCRIPTION
**Pull request by LTGIV**

### CODE REVIEW

**Comment by mlocati** [comment]
I don't have any issues installing GD with `./install-php-extensions gd` (I just checked with `php:5.6-cli`, `php:7.2-cli`, and `php:7.3-cli`).
The command succeeded and the output of `php --ri gd` seems correct:

```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.3
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.6.28
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 0 => 0
```

Could you provide a sample (minimal) dockerfile to replicate the issue you are experiencing?

**Comment by Toflar** [comment]
It works again. I had the same issue last week. It was probably due to some dependency that was missing and that got fixed again in the meantime :)

**Comment by mlocati** [comment]
Closing since it seems unneeded

**Comment by LTGIV** [comment]
@Toflar: Definitely a weird blip that came out of nowhere.

@mlocati: Thanks for reviewing, and glad that it sorted itself out.  Will delete fork now.

**Pull request closed without merging**
