### PR TITLE
Add support for oci8 and pdo_oci extensions no longer bundled with PHP

### LINKED ISSUE #892: oci8/pdo_oci (and imap) have been moved to PECL
### Version of install-php-extensions

latest

### Error description

related with https://github.com/php/php-src/pull/13327

please see the minimal repro Dockerfile below

it currently fails with:
```
#10 93.28 ### INSTALLING REMOTE MODULE oci8 ###
#10 95.32 downloading oci8-3.3.0.tgz ...
#10 95.32 Starting to download oci8-3.3.0.tgz (191,561 bytes)
#10 95.32 .........................................done: 191,561 bytes
#10 95.68 13 source files, building
#10 95.68 running: phpize
#10 95.69 Configuring for:
#10 95.69 PHP Version:             8.4
#10 95.69 PHP Api Version:         20230901
#10 95.69 Zend Module Api No:      20230901
#10 95.69 Zend Extension Api No:   420230901
#10 96.19 Please provide the path to the ORACLE_HOME directory. Use 'instantclient,/path/to/instant/client/lib' if you're compiling with Oracle Instant Client [autodetect] : building in /tmp/pear/temp/pear-build-defaultuserR6sXnr/oci8-3.3.0
#10 96.19 running: /tmp/pear/temp/oci8/configure --with-php-config=/usr/local/bin/php-config --with-oci8
#10 96.28 checking for grep that handles long lines and -e... /usr/bin/grep
#10 96.28 checking for egrep... /usr/bin/grep -E
#10 96.28 checking for a sed that does not truncate output... /usr/bin/sed
#10 96.29 checking for pkg-config... /usr/bin/pkg-config
#10 96.29 checking pkg-config is at least version 0.9.0... yes
#10 96.30 checking for cc... cc
#10 96.35 checking whether the C compiler works... yes
#10 96.35 checking for C compiler default output file name... a.out
#10 96.38 checking for suffix of executables...
#10 96.42 checking whether we are cross compiling... no
#10 96.44 checking for suffix of object files... o
#10 96.45 checking whether the compiler supports GNU C... yes
#10 96.47 checking whether cc accepts -g... yes
#10 96.51 checking for cc option to enable C11 features... none needed
#10 96.54 checking how to run the C preprocessor... cc -E
#10 96.57 checking for icc... no
#10 96.58 checking for suncc... no
#10 96.58 checking for system library directory... lib
#10 96.61 checking if compiler supports -Wl,-rpath,... yes
#10 96.66 checking build system type... x86_64-pc-linux-gnu
#10 96.66 checking host system type... x86_64-pc-linux-gnu
#10 96.66 checking target system type... x86_64-pc-linux-gnu
#10 96.68 checking for PHP prefix... /usr/local
#10 96.68 checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
#10 96.68 checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20230901
#10 96.68 checking for PHP installed headers prefix... /usr/local/include/php
#10 96.69 checking if debug is enabled... no
#10 96.71 checking if zts is enabled... no
#10 96.71 checking for gawk... no
#10 96.71 checking for nawk... nawk
#10 96.71 checking if nawk is broken... no
#10 96.71 checking for Oracle Database OCI8 support... yes, shared
#10 96.71 checking PHP version... expr: non-integer argument
#10 96.71 /tmp/pear/temp/oci8/configure: line 4783: test: : integer expression expected
#10 96.71 /tmp/pear/temp/oci8/configure: line 4785: test: : integer expression expected
#10 96.71 /tmp/pear/temp/oci8/configure: line 4787: test: : integer expression expected
#10 96.71 /tmp/pear/temp/oci8/configure: line 4789: test: : integer expression expected
#10 96.71 CUSTOM--master--10957e498c5eb8600c7289e3ee1101066e49dd1b, ok
#10 96.72 checking OCI8 DTrace support... no
#10 96.76 checking size of long... 8
#10 96.76 checking if we're at 64-bit platform... yes
#10 96.76 configure: WARNING: OCI8 extension: ORACLE_HOME is not set, looking for default Oracle Instant Client instead
#10 96.77 checking Oracle Instant Client directory... configure: error: Oracle Instant Client directory /usr/lib/oracle/.../client64/lib libraries not found. Try --with-oci8=instantclient,DIR
#10 96.79 ERROR: `/tmp/pear/temp/oci8/configure --with-php-config=/usr/local/bin/php-config --with-oci8' failed
```

something needs to be probably adjusted in the installed to account for from php-src to separate repo move

also notice `/.../` (triple dots???) in the path

### Docker image

php:8.4

### Minimal Dockerfile

```Dockerfile
FROM ghcr.io/mvorisek/image-php:8.4-debian-base
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions bcmath
RUN install-php-extensions oci8
# based on https://github.com/php/pecl-database-pdo_oci/pull/1
RUN install-php-extensions php/pecl-database-pdo_oci@33b922ace3
```

### PR DESCRIPTION
**Pull request by mlocati**
Requires https://github.com/php/pecl-database-pdo_oci/issues/2

Close #892

### CODE REVIEW

**Comment by mvorisek** [comment]
Hi @mlocati, I have merged https://github.com/php/pecl-database-pdo_oci/pull/1 and tested this PR with `ghcr.io/mvorisek/image-php:8.4-debian-base` image (as discussed in https://github.com/mlocati/docker-php-extension-installer/issues/892#issuecomment-1972874320).

prepare commans:
```
apt update && apt install git
git clone https://github.com/mlocati/docker-php-extension-installer.git -b oci-php8.4
chmod +x docker-php-extension-installer/install-php-extensions
```

I was able to run `docker-php-extension-installer/install-php-extensions oci8`

but 

`docker-php-extension-installer/install-php-extensions pdo_oci` failed with:
```
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [12.7 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [146 kB]
Fetched 9200 kB in 2s (6032 kB/s)
Reading package lists...
### MARKING PRE-INSTALLED PACKAGES AS IN-USE ###
libaio1 was already set to manually installed.
### INSTALLING REQUIRED PACKAGES ###
# Packages to be kept after installation:
# Packages to be used only for installation: unzip
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package unzip.
(Reading database ... 14780 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-28_amd64.deb ...
Unpacking unzip (6.0-28) ...
Setting up unzip (6.0-28) ...
### INSTALLING REMOTE MODULE pdo_oci ###
WARNING: "pear/PDO_OCI" is deprecated in favor of "channel://http://www.php.net/pdo_oci/ext/pdo_oci"
pear/PDO_OCI requires PHP (version >= 5.0.3, version <= 6.0.0), installed version is 8.4.0-dev
No valid packages found
install failed
```

**Comment by mlocati** [comment]
> Should it be fixed here or in the https://github.com/php/pecl-database-pdo_oci repo?

I don't know: `install-php-extensions` should pass the `with-pdo-oci` option to pecl (exaclly like it passes the `with-oci8` option for oci8)

**Comment by mvorisek** [comment]
It seems https://github.com/php/pecl-database-oci8/blob/main/config.m4 is working. I tried diffing it with https://github.com/php/pecl-database-pdo_oci/blob/main/config.m4, the diff is non-trivial, but the OCI8 can be probably used as a working reference. My question is however why the pdo_oci install was working before the unbundling, did anything changed?

**Comment by mlocati** [comment]
I've tried running this code in two docker containers (launched with `docker run --rm -it php:8.3-cli bash` and `docker run --rm -it ghcr.io/mvorisek/image-php:8.4-debian-base bash`):

```sh
cd /tmp

# Download and extract the oci-php8.4 branch of https://github.com/mlocati/docker-php-extension-installer
curl -sSLf -o- https://github.com/mlocati/docker-php-extension-installer/archive/refs/heads/oci-php8.4.tar.gz | tar xz

# Download and extract the main branch of https://github.com/php/pecl-database-pdo_oci
curl -sSLf -o- https://github.com/php/pecl-database-pdo_oci/archive/refs/heads/main.tar.gz | tar xz

CI=true /tmp/docker-php-extension-installer-oci-php8.4/install-php-extensions /tmp/pecl-database-pdo_oci-main
```

With the official PHP 8.3 docker image everything works just fine
With your PHP 8.4 docker image I have this error:

```
cc -I. -I/tmp/pear/temp/pdo_oci -I/tmp/pear/temp/pear-build-defaultuserYKZKBo/pdo_oci-1.1.0/main -I/tmp/pear/temp/pdo_oci -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/lib/oracle/21.1/client64/lib/sdk/include -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php/ext -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/pdo_oci/pdo_oci.c -MMD -MF pdo_oci.dep -MT pdo_oci.lo  -fPIC -DPIC -o .libs/pdo_oci.o
/tmp/pear/temp/pdo_oci/oci_statement.c: In function 'oci_stmt_fetch':
/tmp/pear/temp/pdo_oci/oci_statement.c:466:9: error: 'S' undeclared (first use in this function)
  466 |         S->last_err = OCIStmtFetch2(S->stmt, S->err, 1, ociori, (sb4) offset, OCI_DEFAULT);
      |         ^
/tmp/pear/temp/pdo_oci/oci_statement.c:466:9: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:217: oci_statement.lo] Error 1
```

I'm sorry I can't help you more (I'm not an expert of OCI).

**Comment by mvorisek** [comment]
Thank you for beiing so patient with me.

In https://github.com/php/pecl-database-pdo_oci/pull/1 I did a mistake. Now I fixed it in https://github.com/php/pecl-database-pdo_oci/commit/be8a277c278f23a3dbe501acf121c1ce26c30c50.

So I can confirm this PR is working. Once again, thank you!

**Comment by mlocati** [comment]
> is anything like done in this PR needed also for unbundled `imap` ext?

Yep.

Just to summarize the list of PHP extensions removed from the PHP main repository:

- `oci8` and `pdo_oci` - see https://github.com/php/php-src/pull/13327
- `imap` - see https://github.com/php/php-src/pull/13190
- `pspell` - see https://github.com/php/php-src/commit/b035cb6c8e31bea351f169b3e9f34fdc562e77e1

Am I missing some?

**Comment by mvorisek** [comment]
only these 4 were unbundled - https://wiki.php.net/rfc/unbundle_imap_pspell_oci8

**Comment by mlocati** [comment]
> is anything like done in this PR needed also for unbundled `imap` ext?

➡️ https://github.com/mlocati/docker-php-extension-installer/pull/900

> only these 4 were unbundled

Thanks for confirming!

**Pull request merged**
