### PR TITLE
Test alpine 3.14

### PR DESCRIPTION
**Pull request by pataar**
Alpine 3.14 is making it's way to the PHP images. (See: https://github.com/docker-library/php/commit/a82fd9b02446334f3bfe2d521263fcee0888a607)

For now, it seems that not all architectures are supported yet. So this PR stays in draft until then.

Related: https://github.com/docker-library/official-images/pull/10379#issuecomment-863396878

### CODE REVIEW

**Comment by mlocati** [comment]
I guess the GitHub Actions will timeout

**Comment by pataar** [comment]
Zookeeper failed because build.xml is not found. Any tips on how to solve this @mlocati?

**Comment by mvorisek** [comment]
probably related with https://github.com/mlocati/docker-php-extension-installer/issues/359 and related Alpine apk issue

**Comment by mlocati** [comment]
Superseded by #364

**Pull request closed without merging**
