### PR TITLE
Add SPX support

### PR DESCRIPTION
**Pull request by 1ed**
Add support for SPX https://github.com/NoiseByNorthwest/php-spx

### CODE REVIEW

**Comment by 1ed** [comment]
Is it OK to use a commit from master instead of a tag? The issue was fixed in https://github.com/NoiseByNorthwest/php-spx/issues/121, but there was no new release since than. (https://github.com/NoiseByNorthwest/php-spx/issues/174)

**Comment by mlocati** [comment]
Sure! We can do something like what we had in https://github.com/mlocati/docker-php-extension-installer/pull/232/files

**Comment by mlocati** [comment]
That's perfect!

**Comment by 1ed** [comment]
Thanks!

**Pull request merged**
